config/routes.rb
Rails.application.routes.draw do
  
  resources :product_views
  get '/product_show', to: 'product_views#create_product_view', as: :product_show
  resources :searches,only:[:index]
  resources :wishlists, only:[:index]
  get '/destroy_wishlisted_product' => 'wishlists#destroy_wishlisted_product', as: :destroy_wishlisted_product
  get '/add_to_wishlist' => 'wishlists#add_to_wishlist', as: :add_to_wishlist
  get '/remove_from_wishlist' => 'wishlists#remove_from_wishlist', as: :remove_from_wishlist
  resources :categories
  resources :notification_belongs
  get 'after_readed', action: :after_read, controller: 'notification_belongs'
  resources :notifications
  get 'carts/index',  to: 'carts#index'
  get 'carts/buy_now',  to: 'carts#buy_now'
  post 'carts/update_qty',  to: 'carts#update_qty'
  get 'carts/update_product_service', to: 'carts#update_product_service'
  get 'orders/time_slot', to: 'orders#time_slot'
  root 'static_pages#home'
  devise_for :users
  resources :users do
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :product_services do
    resources :orders, module: :product_services
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :products do
    resources :orders, module: :products
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  
  resources :product_variants do
    resources :orders, module: :product_variants
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :orders do
    collection do
      get 'time_slot'
    end
  end
  resources :static_pages do
    collection do
      get 'sales_graph_data'
      get 'sales_tabular_data'
      get 'users_graph_data'
      get 'sales_analytical_data_pdf'
    end
  end
  get 'payment/create_payment', to: "payment#create_payment"
  get 'payment/payment_failed', to: "payment#payment_failed"
  get 'payment/order_place', to: "payment#order_place"
end

app/models/product_service.rb
class ProductService < ApplicationRecord
    #For Soft Delete
    include Discard::Model
    searchkick word_middle: [:name, :description]
    has_many :orders, as: :orderable, dependent: :destroy
    has_many :notifications, as: :notifiable, dependent: :destroy
    has_many :product_views, as: :viewable, dependent: :destroy
    belongs_to :user
    has_one_attached :main_image
    has_many_attached :other_images, dependent: :destroy

    belongs_to :category
    after_create :product_service_added_notification
    
    #Notification For All
    def product_service_added_notification 
        @title = I18n.t(:product_service_added_title)
        @content = I18n.t(:product_service_added_content, product_service_name: name, user_name: user.name)
        @notification_data = {"title": @title, "content": @content, "notifiable_type": "ProductService", "notifiable_id": id}
        @user=User.select('id').all 
        Notification.create_notification(@notification_data, @user)
        #BroadCasting Notification
        ActionCable.server.broadcast("notification_channel", {title: @title,content: @content, for_user: "all", icon: "<i class='fa fa-tags' style='font-size:24px;color:orange'></i>"})
    end
    
end

app/controllers/product_services/carts_controller.rb
class ProductServices::CartsController < CartsController
    before_action :set_cart_item
    private
    def set_cart_item
        @cart_item = ProductService.find(params[:product_service_id])
    end
end

app/controllers/product_services/orders_controller.rb
class ProductServices::OrdersController < OrdersController
    before_action :set_orderable
    private
    def set_orderable
        @orderable = ProductService.find(params[:product_service_id])
    end
end

app/controllers/product_services_controller.rb
class ProductServicesController < ApplicationController
  before_action :set_product_service, only: %i[ show edit update soft_destroy destroy ]

  # GET /product_services or /product_services.json
  def index
    if user_signed_in? && current_user.role == "admin"
      @product_services = ProductService.all
    elsif user_signed_in? && current_user.role == "seller"
      @product_services = ProductService.kept.find_by_user_id current_user.id
    else
      @product_services = ProductService.kept
    end
  end

  # GET /product_services/1 or /product_services/1.json
  def show
  end
  
  # ElasticSearch
  def search
    unless params[:query].blank?
      @results = ProductService.search(params[:query])
    end
  end
  # GET /product_services/new
  def new
    @product_service = ProductService.new
    authorize @product_service
  end

  # GET /product_services/1/edit
  def edit
    authorize @product_service
  end

  # POST /product_services or /product_services.json
  def create
    @product_service = ProductService.new(product_service_params)
    @product_service.user_id=current_user.id
    authorize @product_service
    respond_to do |format|
      if @product_service.save
        format.html { redirect_to @product_service, notice: I18n.t('product_service_created') }
        format.json { render :show, status: :created, location: @product_service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_services/1 or /product_services/1.json
  def update
    authorize @product_service
    respond_to do |format|
      if @product_service.update(product_service_params)
        format.html { redirect_to @product_service, notice: I18n.t('product_service_updated') }
        format.json { render :show, status: :ok, location: @product_service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_service.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # SOFT DELETE product_service
  def soft_destroy
    authorize @product_service
    @product_service.discard
    respond_to do |format|
      format.html { redirect_to product_services_url, notice: I18n.t('product_destroyed') }
      format.json { head :no_content }
    end
  end

  # Restore soft deleted product_service
  def restore_soft_deleted
    product_service_id = params[:id]
    ProductService.where(id: product_service_id).update(discarded_at: nil)
    redirect_to product_services_path
  end

  # DELETE /product_services/1 or /product_services/1.json
  def destroy
    authorize @product_service
    @product_service.destroy
    respond_to do |format|
      format.html { redirect_to product_services_url, notice: I18n.t('product_service_destroyed')  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_service
      @product_service = ProductService.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_service_params
      params.require(:product_service).permit(:name, :category_id, :description, :duration, :start_time, :end_time, :price, orders_attributes: [:time])
    end
end

app/helpers/product_services_helper.rb
module ProductServicesHelper
end

app/views/product_services/_form.html.erb
<div class="flex justify-center my-2 mx-4 md:mx-0 ">
  <div class="w-full max-w-xl bg-white rounded-lg shadow-md p-6">
    <%= form_with(model: product_service) do |form| %>
      <% if product_service.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product_service.errors.count, "error") %> prohibited this product_service from being saved:</h2>

          <ul>
            <% product_service.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :category_id, class: "mr-4 devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.select(:category_id,Category.where('category_of = 1').pluck(:name, :id), prompt: "Select Category")%>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :name, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_field :name, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :description, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_area :description, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :duration, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.number_field :duration,placeholder: "in minutes", autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none"%>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :start_time, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.time_field :start_time,placeholder: "in minutes", autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none"%>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :end_time, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.time_field :end_time,placeholder: "in minutes", autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :price, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.number_field :price, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none"%>
        </div>
        <div class="actions">
          <%= form.submit class: "appearance-none block w-25 bg-green-600 font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-white focus:border-gray-500 text-white" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/product_services/edit.html.erb
<h1 class="text-5xl">Editing Service</h1>

<%= render 'form', product_service: @product_service %>

<%= link_to 'Show', @product_service %> |
<%= link_to 'Back', product_services_path %>

app/views/product_services/index.html.erb
<div class="container mx-auto mt-4">
  <%= link_to 'Add a New Service', new_product_service_path, class: "mb-6 appearance-none block w-full bg-green-600 text-white font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-green-500 focus:border-gray-500 text-center" if(user_signed_in? && current_user.role != "buyer") %>
  <% if ProductService.all.length != 0 %>
    <div class="flex flex-col">
      <div class="grid grid-cols-12 gap-4">
        <div class="col-span-3">
          <p class="text-5xl">Services</p>
        </div>
      </div>
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200 mt-4">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Description
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Duration
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Price
                  </th>
                  <th colspan="3" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <% @product_services.each do |product_service| %>
                <tr>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div class="flex items-center">
                      <div class="ml-4">
                        <div class="text-sm font-medium text-gray-900">
                          <%= product_service.name %>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <%= product_service.description %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <%= product_service.duration %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <%= product_service.price %>
                  </td>
                  <td>
                    <%= link_to 'Show', product_service, class: "text-blue-600 hover:text-blue-600"  %>
                  </td>
                  <td>
                    <%= link_to 'Edit', edit_product_service_path(product_service),class: "text-green-600 hover:text-green-600" if user_signed_in? && policy(product_service).edit? %>
                  </td>
                  <td>
                    <% if !product_service.discarded? %>
                      <%= link_to 'Delete', soft_destroy_product_service_path(id: product_service.id), method: :post, data: { confirm: 'Are you sure?' },class: "text-red-600 hover:text-delete-600"  if user_signed_in? && policy(product_service).soft_destroy? %>
                    <% else %>
                          <%=link_to "Undelete", restore_soft_deleted_product_service_path(id: product_service.id), data: { confirm: "Are you sure?" }, method: :post, class: "bg-inherit text-green-600 hover:text-green-600 visited:text-green-700", data: { confirm: "Are you sure?"} if policy(product).restore_soft_deleted? %>
                        <% end %>
                    <% if user_signed_in? && current_user.role == "admin" && product_service.discarded? %>
                      <%= link_to 'Permanent Delete', product_service, method: :delete, data: { confirm: 'Are you sure?' },class: "text-red-600 hover:text-delete-600"  if user_signed_in? && policy(product).destroy? %>
                  </td>
                  <% end %>
                </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/product_services/new.html.erb
<h1 class="text-5xl">New Service</h1>

<%= render 'form', product_service: @product_service %>

<%= link_to 'Back', product_services_path %>

app/views/product_services/search.html.erb
<% @results.each do |results| %>
    <hr>
    title : 
    <% if results.respond_to? :highlight %>
    <%= results.highlight.name.to_a.map{|item| %Q{"#{item}"}}.join() %>
    <%= results.highlight.description %>
    <%else %>
    <%= results.name %>
    <%= results.description%>
    <% end %>
    <hr>
<% end %>

app/views/product_services/show.html.erb
<div class="container mx-auto"> 
  <div class="grid grid-cols-4"> 
    <div class="col-span-2">
      <div class="max-w-md mx-auto text-base p-10 bg-white shadow-lg rounded-lg my-20 mr-5">
          <p id="notice"><%= notice %></p>

          <p class="text-sm mb-2">
            <strong>Name:</strong>
            <%= @product_service.name %>
          </p>

          <p class="text-sm mb-2">
            <strong>Description:</strong>
            <%= @product_service.description %>
          </p>

          <p class="text-sm mb-2">
            <strong>Duration:</strong>
             <%= @product_service.duration %>
          </p>

          <p class="text-sm mb-2">
            <strong>Price:</strong>
            <%= @product_service.price %>
          </p>

          <button>
            <%= link_to 'Edit', edit_product_service_path(@product_service),class: "appearance-none block w-28 bg-blue-600 text-gray-100 font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-blue-500 focus:outline-none focus:bg-white focus:border-gray-500"  if user_signed_in? && policy(@product_service).edit? %>
          </button>
          <%= render partial: 'orders/form', locals: {orderable: @product_service} %>
      </div>
    </div>
    <div class="col-span-2 ">
      <div class="max-w-md mx-auto text-base p-10 rounded-lg mt-10 ml-0">
        <div id="time_slots"></div>
      </div>
    </div>
  </div>
</div>