config/routes.rb
Rails.application.routes.draw do
  
  resources :product_views
  get '/product_show', to: 'product_views#create_product_view', as: :product_show
  resources :searches,only:[:index]
  resources :wishlists, only:[:index]
  get '/destroy_wishlisted_product' => 'wishlists#destroy_wishlisted_product', as: :destroy_wishlisted_product
  get '/add_to_wishlist' => 'wishlists#add_to_wishlist', as: :add_to_wishlist
  get '/remove_from_wishlist' => 'wishlists#remove_from_wishlist', as: :remove_from_wishlist
  resources :categories
  resources :notification_belongs
  get 'after_readed', action: :after_read, controller: 'notification_belongs'
  resources :notifications
  get 'carts/index',  to: 'carts#index'
  get 'carts/buy_now',  to: 'carts#buy_now'
  post 'carts/update_qty',  to: 'carts#update_qty'
  get 'carts/update_product_service', to: 'carts#update_product_service'
  get 'orders/time_slot', to: 'orders#time_slot'
  root 'static_pages#home'
  devise_for :users
  resources :users do
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :product_services do
    resources :orders, module: :product_services
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :products do
    resources :orders, module: :products
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  
  resources :product_variants do
    resources :orders, module: :product_variants
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :orders do
    collection do
      get 'time_slot'
    end
  end
  resources :static_pages do
    collection do
      get 'sales_graph_data'
      get 'sales_tabular_data'
      get 'users_graph_data'
      get 'sales_analytical_data_pdf'
    end
  end
  get 'payment/create_payment', to: "payment#create_payment"
  get 'payment/payment_failed', to: "payment#payment_failed"
  get 'payment/order_place', to: "payment#order_place"
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  #For Soft Delete
  include Discard::Model
  has_many :orders, as: :orderable, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :product_views, dependent: :destroy
  has_one_attached :main_image, dependent: :destroy
  has_many_attached :other_images, dependent: :destroy
  belongs_to :product
  has_many :wishlists, dependent: :destroy
  belongs_to :user
  validates_uniqueness_of :batch_no
  #validates :other_images, presence: true
  
  after_create :product_added_notification 
  before_update :notification_if_item_is_wishlisted

  #For Notification
  def product_added_notification 
    @title = I18n.t(:product_added_title)
    @content = I18n.t(:product_added_content, product_name: product.name, user_name: user.name)
    @notification_data = {"title": @title, "content": @content, "notifiable_type": "ProductVariant", "notifiable_id": id}
    @user=User.select('id').all 
    Notification.create_notification(@notification_data, @user)
    #BroadCasting Notification
    ActionCable.server.broadcast("notification_channel", {title: @title,content: @content, for_user: "all", icon: "<i class='fa fa-tags' style='font-size:24px;color:orange'></i>"})
  end

  #Wishlist
  def notification_if_item_is_wishlisted
    if quantity_was == 0
      wishlist_data = Wishlist.select('user_id').where(product_variant_id: id)
      @users=[]
      wishlist_data.each do |user|
        @users << user.user_id
        #BroadCasting Notification
        ActionCable.server.broadcast("notification_channel", {title: I18n.t(:stock_back_title),content: I18n.t(:stock_back_content, product_name: product.name), for_user: "specific_user", current_user: user.user_id, icon: "<i class='fa fa-tags' style='font-size:24px;color:orange'></i>"})
      end
      @title = I18n.t(:stock_back_title)
      @content = I18n.t(:stock_back_content, product_name: product.name)
      @notification_data = {"title": @title, "content": @content, "notifiable_type": "ProductVariant", "notifiable_id": id}
      @user=User.select('id').where(id: @users)
      Notification.create_notification(@notification_data, @user)
    end 
  end

end

app/controllers/product_variants/orders_controller.rb
class ProductVariants::OrdersController < OrdersController
    before_action :set_orderable
    private
    def set_orderable
        @orderable = ProductVariant.find(params[:product_variant_id])
    end
end

app/controllers/product_variants_controller.rb
class ProductVariantsController < ApplicationController
  before_action :set_product_variant, only: %i[ show edit update soft_destroy destroy ]

  # GET /product_variants/1 or /product_variants/1.json
  def show
  end

  # GET /product_variants/new
  def new
    @product_variant = ProductVariant.new
    authorize @product_variant
  end

  # GET /product_variants/1/edit
  def edit
    authorize @product_variant
  end

  # POST /product_variants or /product_variants.json
  def create
    @product_variant = ProductVariant.new(product_variant_params)
    @product_variant.user_id=current_user.id
    authorize @product_variant
    respond_to do |format|
      if @product_variant.save
        format.html { redirect_to @product_variant, notice: I18n.t('product_variant_created') }
        format.json { render :show, status: :created, location: @product_variant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_variants/1 or /product_variants/1.json
  def update
    authorize @product_variant
    respond_to do |format|
      if @product_variant.update(product_variant_params)
        format.html { redirect_to @product_variant, notice: I18n.t('product_variant_updated')  }
        format.json { render :show, status: :ok, location: @product_variant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # SOFT DELETE /product_variants/1 or /product_variants/1.json
  def soft_destroy
    authorize @product_variant
    @product_variant.discard
    respond_to do |format|
      format.html { redirect_to @product_variant.product, notice: I18n.t('product_destroyed') }
      format.json { head :no_content }
    end
  end

  # Restore soft deleted product_variant
  def restore_soft_deleted
    product_variant_id = params[:id]
    ProductVariant.where(id: product_variant_id).update(discarded_at: nil)
    redirect_to ProductVariant.find(product_variant_id).product
  end

  # DELETE /product_variants/1 or /product_variants/1.json
  def destroy
    authorize @product_variant
    @product_variant.destroy
    respond_to do |format|
      format.html { redirect_to @product_variant.product, notice: I18n.t('product_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_variant
      @product_variant = ProductVariant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_variant_params
      params.require(:product_variant).permit(:batch_no, :weight, :price, :quantity, :expiry, :product_id, :discarded_at, :remove_main_image, :main_image, other_images: [])
    end
end

app/helpers/product_variants_helper.rb
module ProductVariantsHelper
end

app/views/product_variants/_all_product_variant.html.erb
<div class="container mt-14  mx-auto" style="width:75vw; margin-auto">
  <% @product_variants.includes(:main_image_attachment).each do |product_variant| %>
    <div class="grid grid-cols-12 gap-3 mx-auto">
      <div class ="col-span-4  mx-auto" >
      <%= link_to product_variant do  %>
            <% if product_variant.main_image.attached? %>
              <%= image_tag product_variant.main_image, class: "h-full", style: "min-width: 50%;max-width: 90%;min-height: 256px;max-height: 456px;"%>
            <% else %>
              <%= image_tag image_url("no_image.jpg"), class:"h-full", style: "min-width: 50%;max-width: 60%;min-height: 256px;max-height: 456px;" %>
            <% end %>
      <% end %>
      </div>
      <div class = "mx-auto col-span-5 ml-5">
      <%= link_to product_variant do  %>
        <div class="mb-2">
          <span class="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Batch No : 
          </span>
          <span class="text-sm font-medium text-gray-900">
            <%= product_variant.batch_no %>
          </span>
        </div>
        <div class="mb-2">
          <span class="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Weight
          </span>
          <span class="text-sm font-medium text-gray-900">
            <%= product_variant.weight %>
          </span>
        </div>
        <div class="mb-2">
          <span class="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Price
          </span>
          <span class="text-sm font-medium text-gray-900">
            <%= product_variant.price %>
          </span>
        </div>
        <div class="mb-2">
          <span class="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Quantity
          </span>
          <span class="text-sm font-medium text-gray-900">
            <%= product_variant.quantity %>
          </span>
        </div>
        <div class="mb-2">
          <span class="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Expiry
          </span>
          <span class="text-sm font-medium text-gray-900">
            <%= product_variant.expiry %>
          </span>
        </div>
        <div class="mb-2">
          <span class=" text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Product Id
          </span>
          <span class="text-sm font-medium text-gray-900">
            <%= product_variant.product_id %>
          </span>
        </div>
        <% if user_signed_in? && current_user.role == "admin" && product_variant.discarded? %>
          <div class="text-center w-full  text-3xl head text-red-500">Deleted</div>
        <% end %>
        <% if product_variant.discarded? %>
          <%=link_to "Undelete", restore_soft_deleted_product_variant_path(id: product_variant.id), data: { confirm: "Are you sure?" }, method: :post, class: "bg-inherit text-green-600 hover:text-green-600 visited:text-green-700", data: { confirm: "Are you sure?"} if policy(product_variant).restore_soft_deleted? %>
        <% else %>
          <%= link_to 'Delete', soft_destroy_product_variant_path(id: product_variant.id), method: :post, data: { confirm: 'Are you sure?'},class: "text-red" if user_signed_in? && policy(product_variant).soft_destroy? %>
        <% end %>
      <% end %>
      <br>
      <%= link_to 'Permanent Delete', product_variant, method: :delete, data: { confirm: 'Are you sure?'},class: "text-red" if user_signed_in? && policy(product_variant).destroy? %>
      </div>
    </div>
    <hr>
    <br>
  <% end %>
</div>

app/views/product_variants/_form.html.erb
<div class="flex justify-center my-2 mx-4 md:mx-0 ">
  <div class="w-full max-w-xl bg-white rounded-lg shadow-md p-6">
    <%= form_with(model: product_variant) do |form| %>
      <% if product_variant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product_variant.errors.count, "error") %> prohibited this product_variant from being saved:</h2>
          <ul>
            <% product_variant.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :batch_no, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_field :batch_no, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :weight, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_area :weight, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :price, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_field :price, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :quantity, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.number_field :quantity, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :expiry, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.date_field :expiry, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :product_id, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.select(:product_id, Product.pluck(:name, :id), :selected => params[:pid]) %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :main_image,"Images", class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.file_field :main_image, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :other_images,"Images", class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.file_field :other_images, multiple: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
        <div class="actions">
          <%= form.submit class: "appearance-none block w-25 bg-green-600 font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-white focus:border-gray-500 text-white" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/product_variants/_product_image.html.erb
<div class="main">
  <div class="slider slider-for">
    <% if @product_variant.other_images.length != 0 %>
      <% @product_variant.other_images.each do |product_image| %>
        <div class="main-image" style="height:60vh">
          <%= image_tag product_image, class: "height:full, mx-auto", style:"min-width: 50%;max-width: 90%;min-height: 256px;max-height: 456px;"%>
        </div>
      <% end %>
    <% else %>
       <%= image_tag image_url("no_image.jpg"), class:"h-full" %>
    <% end %>
  </div>
  
  <div class="slider slider-nav">
    <% @product_variant.other_images.each do |product_image| %>
      <div class="bottom-image">
        <%= image_tag product_image,class: 'h-full', style: "display: flex;justify-content: center;" %>
      </div>
    <% end %>
  </div>
</div>

app/views/product_variants/edit.html.erb
<h1 class="text-5xl">Editing Product Variant</h1>

<%= render 'form', product_variant: @product_variant %>

<%= link_to 'Show', @product_variant %> |
<%= link_to 'Back', product_variants_path %>

app/views/product_variants/new.html.erb
<h1 class="text-5xl">New Product Variant</h1>

<%= render 'form', product_variant: @product_variant %>

<%= link_to 'Back', product_variants_path %>

app/views/product_variants/show.html.erb
<div class="container ml-12 w-9/12 mt-14">
  <p id="notice"><%= notice %></p>
  <div class="grid grid-cols-12 gap-1">
    <div class="col-span-5 images h-36">
      <p class="mb-3 float-right">
      <!--Product Image-->
      <%= render partial: "product_variants/product_image"%>
      </p>
    </div>
    <div class="col-span-5 ml-28">

      <p class="mb-2">
        <strong>Batch no:</strong>
        <%= @product_variant.batch_no %>
      </p>

      <p class="mb-2">
        <strong>Weight:</strong>
        <%= @product_variant.weight %>
      </p>

      <p class="mb-2">
        <strong>Price:</strong>
        <%= @product_variant.price %>
      </p>

      <p class="mb-2">
        <strong>Quantity:</strong>
        <%= @product_variant.quantity %>
      </p>

      <p class="mb-2">
        <strong>Expiry:</strong>
        <%= @product_variant.expiry %>
      </p>

      <p class="mb-2">
        <strong>Product:</strong>
        <%= @product_variant.product_id %>
      </p>
      <% if @product_variant.quantity != 0 %>
        <%= render partial: "orders/form", locals: {orderable: @product_variant} %>
      <% else %>
        <div class="appearance-none w-auto rounded-lg text-gray-100 font-bold border text-center border-gray-200 py-4 px-3 leading-tight" style="background-color:orange">Out Of Stock</div>
        <% if user_signed_in? %>
          <!--Wishlist-->
          <% if Wishlist.where("product_variant_id = #{@product_variant.id} AND user_id = #{current_user.id}").count == 0 %>
            <button type="button" id="addWishlistButton" class="inline appearance-none w-full bg-green-600 rounded-lg text-gray-100 font-bold border border-gray-200 py-3 px-3 leading-tight hover:bg-green-500 focus:opacity-70 focus:outline-none focus:border-gray-500" onclick="addToWishlist(<%= @product_variant.id %>,<%= current_user.id %>,'<%= add_to_wishlist_path %>')">
              Add To Wishlist
            </button>
            <button type="button" id="removeFromWishlist" class="hidden appearance-none w-full bg-red-600 rounded-lg text-gray-100 font-bold border border-gray-200 py-3 px-3 leading-tight hover:bg-red-500 focus:opacity-70 focus:outline-none focus:border-gray-500"onclick="removeFromWishlist(<%= @product_variant.id %>,<%= current_user.id %>,'<%= remove_from_wishlist_path %>')">
              Remove From Wishlist
            </button>
          <% else %>
            <button type="button" id="addWishlistButton" class="hidden appearance-none w-full bg-green-600 rounded-lg text-gray-100 font-bold border border-gray-200 py-3 px-3 leading-tight hover:bg-green-500 focus:opacity-70 focus:outline-none focus:border-gray-500" onclick="addToWishlist(<%= @product_variant.id %>,<%= current_user.id %>,'<%= add_to_wishlist_path %>')">
              Add To Wishlist
            </button>
            <button type="button" id="removeFromWishlist" class="inline appearance-none w-full bg-red-600 rounded-lg text-gray-100 font-bold border border-gray-200 py-3 px-3 leading-tight hover:bg-red-500 focus:opacity-70 focus:outline-none focus:border-gray-500"onclick="removeFromWishlist(<%= @product_variant.id %>,<%= current_user.id %>,'<%= remove_from_wishlist_path %>')">
              Remove From Wishlist
            </button>
          <% end %>  
        <% end %>      
      <% end %>
      <%= link_to 'Edit', edit_product_variant_path(@product_variant, pid: @product_variant.product_id) if user_signed_in? && policy(@product_variant).edit?  %> |
      <%= link_to 'Back', products_path %>
    </div>
  </div>
</div> 

<!--Javascript-->
<%= javascript_pack_tag 'wishlist' %> 
<script>
  $.getJSON("https://api.ipify.org/?format=json", function(e) {
    $.ajax({
      type: 'get',
      data: "user_ip="+e.ip+"&product_variant_id=<%= @product_variant.id %>",
      url: '<%= product_show_path %>'
    })
  });
  
</script>