config/routes.rb
Rails.application.routes.draw do
  
  resources :product_views
  get '/product_show', to: 'product_views#create_product_view', as: :product_show
  resources :searches,only:[:index]
  resources :wishlists, only:[:index]
  get '/destroy_wishlisted_product' => 'wishlists#destroy_wishlisted_product', as: :destroy_wishlisted_product
  get '/add_to_wishlist' => 'wishlists#add_to_wishlist', as: :add_to_wishlist
  get '/remove_from_wishlist' => 'wishlists#remove_from_wishlist', as: :remove_from_wishlist
  resources :categories
  resources :notification_belongs
  get 'after_readed', action: :after_read, controller: 'notification_belongs'
  resources :notifications
  get 'carts/index',  to: 'carts#index'
  get 'carts/buy_now',  to: 'carts#buy_now'
  post 'carts/update_qty',  to: 'carts#update_qty'
  get 'carts/update_product_service', to: 'carts#update_product_service'
  get 'orders/time_slot', to: 'orders#time_slot'
  root 'static_pages#home'
  devise_for :users
  resources :users do
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :product_services do
    resources :orders, module: :product_services
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :products do
    resources :orders, module: :products
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  
  resources :product_variants do
    resources :orders, module: :product_variants
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :orders do
    collection do
      get 'time_slot'
    end
  end
  resources :static_pages do
    collection do
      get 'sales_graph_data'
      get 'sales_tabular_data'
      get 'users_graph_data'
      get 'sales_analytical_data_pdf'
    end
  end
  get 'payment/create_payment', to: "payment#create_payment"
  get 'payment/payment_failed', to: "payment#payment_failed"
  get 'payment/order_place', to: "payment#order_place"
end

app/controllers/product_views_controller.rb
class ProductViewsController < ApplicationController

  def create_product_view
    unless user_signed_in? &&(current_user.role =="admin" || current_user.role =="seller")
      previous_view=ProductView.where(user_ip: params[:user_ip], product_variant_id: params[:product_variant_id]).count
      if previous_view == 0
          ProductView.create(user_ip: params[:user_ip],product_variant_id: params[:product_variant_id])
      end
    end
  end
  
  # Only allow a list of trusted parameters through.
  def product_view_params
    params.require(:product_view).permit(:product_variant_id, :user_ip)
  end
end

app/helpers/product_views_helper.rb
module ProductViewsHelper
    def product_name(product_variant)
        Product.find(product_variant.product_id).name
    end
end

app/views/product_views/_form.html.erb
<%= form_with(model: product_view) do |form| %>
  <% if product_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_view.errors.count, "error") %> prohibited this product_view from being saved:</h2>

      <ul>
        <% product_view.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :viewable_id %>
    <%= form.text_field :viewable_id %>
  </div>

  <div class="field">
    <%= form.label :user_ip %>
    <%= form.text_field :user_ip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_views/edit.html.erb
<h1>Editing Product View</h1>

<%= render 'form', product_view: @product_view %>

<%= link_to 'Show', @product_view %> |
<%= link_to 'Back', product_views_path %>

app/views/product_views/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container mx-auto mt-4">
  <%= link_to 'New Product View', new_product_view_path, class: "mb-6 appearance-none block w-full bg-green-600 text-gray-100 font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-green-500 focus:border-gray-500 text-center" if(user_signed_in? && current_user.role != "buyer") %>
  <% if ProductView.all.length != 0 %>
    <div class="flex flex-col">
      <div class="grid grid-cols-12 gap-4">
        <div class="col-span-3">
          <p class="text-5xl">Product Views</p>
        </div>
      </div>

      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200 mt-4">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Description
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Duration
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Price
                  </th>
                  <th colspan="3" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <% @product_views.each do |product_view| %>
                  <tr>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <%= product_view.viewable_id %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <%= product_view.user_ip %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <%= link_to 'Show', product_view %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <%= link_to 'Edit', edit_product_view_path(product_view) %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <%= link_to 'Destroy', product_view, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/product_views/new.html.erb
<h1>New Product View</h1>

<%= render 'form', product_view: @product_view %>

<%= link_to 'Back', product_views_path %>

app/views/product_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Viewable:</strong>
  <%= @product_view.viewable_id %>
</p>

<p>
  <strong>User ip:</strong>
  <%= @product_view.user_ip %>
</p>

<%= link_to 'Edit', edit_product_view_path(@product_view) %> |
<%= link_to 'Back', product_views_path %>