config/routes.rb
Rails.application.routes.draw do
  
  resources :product_views
  get '/product_show', to: 'product_views#create_product_view', as: :product_show
  resources :searches,only:[:index]
  resources :wishlists, only:[:index]
  get '/destroy_wishlisted_product' => 'wishlists#destroy_wishlisted_product', as: :destroy_wishlisted_product
  get '/add_to_wishlist' => 'wishlists#add_to_wishlist', as: :add_to_wishlist
  get '/remove_from_wishlist' => 'wishlists#remove_from_wishlist', as: :remove_from_wishlist
  resources :categories
  resources :notification_belongs
  get 'after_readed', action: :after_read, controller: 'notification_belongs'
  resources :notifications
  get 'carts/index',  to: 'carts#index'
  get 'carts/buy_now',  to: 'carts#buy_now'
  post 'carts/update_qty',  to: 'carts#update_qty'
  get 'carts/update_product_service', to: 'carts#update_product_service'
  get 'orders/time_slot', to: 'orders#time_slot'
  root 'static_pages#home'
  devise_for :users
  resources :users do
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :product_services do
    resources :orders, module: :product_services
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :products do
    resources :orders, module: :products
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  
  resources :product_variants do
    resources :orders, module: :product_variants
    member do
      post 'soft_destroy'
      post 'restore_soft_deleted'
    end
  end
  resources :orders do
    collection do
      get 'time_slot'
    end
  end
  resources :static_pages do
    collection do
      get 'sales_graph_data'
      get 'sales_tabular_data'
      get 'users_graph_data'
      get 'sales_analytical_data_pdf'
    end
  end
  get 'payment/create_payment', to: "payment#create_payment"
  get 'payment/payment_failed', to: "payment#payment_failed"
  get 'payment/order_place', to: "payment#order_place"
end

app/models/product.rb
class Product < ApplicationRecord
    #For Soft Delete
    include Discard::Model
    searchkick word_middle: [:name]
    has_many :orders, as: :orderable, dependent: :destroy
    has_many :product_variants, dependent: :destroy
    has_many :notifications, as: :notifiable, dependent: :destroy
    has_one_attached :main_image
    belongs_to :category
    accepts_nested_attributes_for :product_variants
    belongs_to :user
    validates :category_id, presence: true
    #validates :main_image, presence: true
    
    
end

app/models/product_view.rb
class ProductView < ApplicationRecord
  belongs_to :product_variant
end

app/controllers/products/orders_controller.rb
class Products::OrdersController < OrdersController
    before_action :set_orderable
    private
    def set_orderable
        @orderable = Product.find(params[:product_id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update soft_destroy destroy ]
  include ProductsHelper
  # GET /products or /products.json
  def index
    if user_signed_in?
      products, heading =  AllProductService.product_index(params[:category],current_user)
    else
      products, heading = AllProductService.product_index(params[:category],nil)
    end
    @pagy,@products = pagy(products)
    @heading = heading
  end

  # GET /products/1 or /products/1.json
  def show
    if user_signed_in? and current_user.role =="admin"
      @pagy,@product_variants = pagy(ProductVariant.where(product_id: @product.id))
    else
      @pagy,@product_variants = pagy(ProductVariant.where(product_id: @product.id).kept)
    end
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
    @product.product_variants.build
  end

  # GET /products/1/edit
  def edit
    authorize @product
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id=current_user.id
    authorize @product
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: I18n.t('product_created') }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    authorize @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: I18n.t('product_updated') }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # SOFT DELETE /products/1 or /products/1.json
  def soft_destroy
    authorize @product
    @product.discard
    respond_to do |format|
      format.html { redirect_to products_url, notice: I18n.t('product_destroyed') }
      format.json { head :no_content }
    end
  end

  # Restore soft deleted products
  def restore_soft_deleted
    product_id = params[:id]
    Product.where(id: product_id).update(discarded_at: nil)
    redirect_to products_path
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    # authorize @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: I18n.t('product_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:id, :category_id, :name, :code, :description, :price, :quantity, :remove_main_image, :main_image, product_variants_attributes: [:batch_no, :weight, :price, :quantity, :expiry, :products_id,:user_id, :remove_main_image, :main_image, other_images: []])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form_edit.html.erb
<div class="flex justify-center my-2 mx-4 md:mx-0 ">
  <div class="w-full max-w-xl bg-white rounded-lg shadow-md p-6">
    <%= form_for @product do |form| %>
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
            <% product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :name, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_field :name, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none", type:'text' %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :description, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_area :description, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none", type:'text' %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :main_image, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.file_field :main_image, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
  
      <div class="actions">
        <%= form.submit class: "appearance-none block w-25 bg-green-600 font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-white focus:border-gray-500 text-white" %>
      </div>
<% end %>

app/views/products/_form_new.html.erb
<div class="flex justify-center my-2 mx-4 md:mx-0 ">
  <div class="w-full max-w-xl bg-white rounded-lg shadow-md p-6">
    <%= form_for @product do |form| %>
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
            <% product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :category_id, class: "mr-4 devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.select(:category_id,Category.where("category_of = 0").pluck(:name, :id), prompt: "Select Category")%>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :name, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_field :name, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none", type:'text' %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :description, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.text_area :description, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none", type:'text' %>
        </div>
        <div class="w-full md:w-full px-3 mb-6">
            <%= form.label :main_image,"Logo", class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= form.file_field :main_image, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
        </div>
  
        <h1>Product Variants</h1>
        <%= form.fields_for :product_variants do |builder| %>
          <div class="w-full md:w-full px-3 mb-6">
            <%= builder.label :batch_no, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= builder.text_field :batch_no, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
          </div>
          <div class="w-full md:w-full px-3 mb-6">
            <%= builder.label :weight, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= builder.text_field :weight, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
          </div>
          <div class="w-full md:w-full px-3 mb-6">
            <%= builder.label :price, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= builder.text_field :price, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
          </div>
          <div class="w-full md:w-full px-3 mb-6">
            <%= builder.label :quantity, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= builder.number_field :quantity, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
          </div>
          <div class="w-full md:w-full px-3 mb-6">
            <%= builder.label :expiry, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>&ensp;
            <%= builder.date_field :expiry, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
          </div>
          <div class="w-full md:w-full px-3 mb-6">
            <%= builder.label :main_image, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= builder.file_field :main_image, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
          </div>
          <div class="w-full md:w-full px-3 mb-6">
            <%= builder.label :other_images, class: "devise-label block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
            <%= builder.file_field :other_images, multiple: true, autofocus: true, autocomplete: "name", class:"appearance-none block w-full bg-white text-gray-900 font-medium border border-gray-400 rounded-lg py-3 px-3 leading-tight focus:outline-none" %>
          </div>
          <%= builder.hidden_field :user_id, value: current_user.id%>
        <% end %>
    
        <div class="actions">
          <%= form.submit class: "appearance-none block w-25 bg-green-600 font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-white focus:border-gray-500 text-white" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1 class="text-5xl">Editing Product</h1>
<%= render 'form_edit', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container mx-auto mt-4">
  <div class="flex flex-col">
      <%= link_to 'Add a New Product', new_product_path,class: "mb-6 appearance-none block w-full text-center bg-green-600 text-white font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-green focus:border-gray-500" if(user_signed_in? && current_user.role != "buyer") %>
      <div class="text-3xl mt-5">
        <%= @heading %>
      </div>
  </div>
    <% if !@products.nil? %>
      <div class="flex flex-col">
        <ul class="result">
          <% @products.includes(:main_image_attachment).each do |product| %>
              <li>
                <div class="card cardsearchcloth">
                  <%= link_to product, class: "bg-inherit" do %>
                    <% if product.main_image.attached? %>
                      <%= image_tag product.main_image, class:"w-full" %>
                    <% else %>
                      <%= image_tag image_url("no_image.jpg"), class:"w-full" %>
                    <% end %>
                    <div class="card-body" style="text-align:left">
                      <div class="card-product-name text-center">
                        <%= product.name %>
                      </div>
                  <% end %>
                    <% if user_signed_in? && current_user.role == "admin" && product.discarded? %>
                    <div class="text-center w-full  text-1xl head text-red-500">Deleted</div>
                    <% end %>
                      <div>
                        <%= link_to 'Edit', edit_product_path(product),class: "text-green-600 hover:text-green-600" if user_signed_in? && policy(product).edit? %>
                      </div>
                      <div>
                        <% if !product.discarded? %>
                          <%= link_to 'Delete', soft_destroy_product_path(id: product.id), method: :post, data: { confirm: 'Are you sure?' },class: "text-red-600 hover:text-delete-600"  if user_signed_in? && policy(product).soft_destroy? %>
                        <% else %>
                          <%=link_to "Undelete", restore_soft_deleted_product_path(id: product.id), data: { confirm: "Are you sure?" }, method: :post, class: "bg-inherit text-green-600 hover:text-green-600 visited:text-green-700", data: { confirm: "Are you sure?"} if policy(product).restore_soft_deleted?%>
                        <% end %>
                      </div>
                    <% if user_signed_in? && current_user.role == "admin" && product.discarded? %>
                      <div>
                        <%= link_to 'Permanent Delete', "/products/"+product.id.to_s, method: :delete, data: { confirm: 'Are you sure?' },class: "text-red-600 hover:text-delete-600"  if user_signed_in? && policy(product).destroy? %>
                      </div>
                    <% end %>
                  </div>
              </li>
            <% end %>
        </ul>
        <div class="view-more"> 
          <button class="">View All</button>
        </div>
        <div class="pages mx-auto mt-2 mb-2"><%== pagy_nav(@pagy) %></div>
      </div>

      
        <!--Product Cards-->
        <div class="mt-5">
          <ul class="result">
            <% @products.each do |product| %>
              <% product.product_variants.includes(:main_image_attachment).each do |product_variant| %>
                <%= link_to product_variant, class: "bg-inherit" do %>
                  <li>
                    <div class="card cardsearchcloth">
                        <% if product_variant.main_image.attached? %>
                          <%= image_tag product_variant.main_image,class: "product-image mx-auto" %>
                        <% else %>
                          <%= image_tag image_url("no_image.jpg"), class:"h-full", style: "height: 245px;width: auto;border-radius: 4px;margin: auto;margin-top: 7px;" %>
                        <% end %>
                      <div class="card-body" style="text-align:left">
                        <div class="card-product-name">
                          <%= product_variant.product.name %>
                        </div>
                        <span style="color:red;font-weight:600;font-size:18px;">₹ <%= product_variant.price %></span>
                        <div style="font-weight:600;font-size:12px;">(Inclusive of all taxes)</div>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>
    <% end %>
</div>

app/views/products/new.html.erb
<h1 class="text-5xl">New Product</h1>

<%= render 'form_new', product: @product %>

<%= button_to 'Back', products_path, method: :get,class: "appearance-none block w-25 bg-blue-600 font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-blue-500 focus:outline-none focus:bg-white focus:border-gray-500 text-white" %>

app/views/products/search.html.erb
<% @results.each do |results| %>
    <hr>
    title :  <%= results.name %>
    <hr>
<% end %>

app/views/products/show.html.erb
<div class="container mx-auto mt-4">
  <p id="notice"><%= notice %></p>
  <%= link_to 'Add a New Product Variant', new_product_variant_path(pid: @product.id),class: "mb-6 appearance-none block w-full bg-green-600 text-white font-bold border border-gray-200 rounded-lg py-3 px-3 leading-tight hover:bg-green-500 focus:outline-none focus:bg-green-500 focus:border-gray-500 text-center" if(user_signed_in? && current_user.role != "buyer") %>
  <div class="text-5xl">
    <div class="float-left h-12 mr-4">
      <% if @product.main_image.attached? %>
        <%= image_tag @product.main_image, class:"h-full" %>
      <% else %>
       <%= image_tag image_url("no_image.jpg"), class:"h-full" %>
      <% end %>
    </div>
    <div id="product-name">
      <%= @product.name %>
    </div>
  </div>
  
  <%= link_to 'Edit', edit_product_path(@product),class:"text-2xl text-blue-500" if user_signed_in? && policy(@product).edit? %>
  <%= render partial: 'product_variants/all_product_variant'%>
</div>

 